# Copyright (c) 2019 R. Tohid
#
# Distributed under the Boost Software License, Version 1.0. (See a copy at
# http://www.boost.org/LICENSE_1_0.txt)

FROM phycfg:python-vanilla

RUN git clone https://github.com/rtohid/phycfg.git